"""Centralized Traditional Chinese UI labels for Whisper UI."""
# ruff: noqa: RUF001

from __future__ import annotations

# -- Page titles --
PAGE_UPLOAD = "上傳"

# -- Navigation --
NAV_DASHBOARD = "首頁"
NAV_UPLOAD = "上傳"
NAV_JOBS = "任務"

# -- Dashboard --
DASHBOARD_HEADER = "總覽"
DASHBOARD_RECENT_SECTION = "最近完成的轉錄"
DASHBOARD_GREETING_MORNING = "早安"
DASHBOARD_GREETING_AFTERNOON = "午安"
DASHBOARD_GREETING_EVENING = "晚安"
DASHBOARD_GREETING_WITH_NAME = "{greeting}，{name}"
DASHBOARD_GREETING_GUEST = "{greeting}"
DASHBOARD_HERO_IN_FLIGHT = "進行中的任務"
DASHBOARD_HERO_ETA = "預估剩餘約 {minutes} 分鐘"
DASHBOARD_HERO_ETA_UNKNOWN = "進度持續更新中"
DASHBOARD_STAGE_DOWNLOAD = "下載"
DASHBOARD_STAGE_PREPARE = "預處理"
DASHBOARD_STAGE_TRANSCRIBE = "辨識"
DASHBOARD_STAGE_DIARIZE = "分離"
DASHBOARD_STAGE_CORRECT = "校驗"
DASHBOARD_STAGE_EXPORT = "匯出"
DASHBOARD_QUICK_ACTION_FILE = "上傳檔案"
DASHBOARD_QUICK_ACTION_FOLDER = "上傳資料夾"
DASHBOARD_QUICK_ACTION_URL = "貼上網址連結"
DASHBOARD_QUICK_ACTION_FILE_DESC = "從本機選取音訊或影片檔案"
DASHBOARD_QUICK_ACTION_FOLDER_DESC = "批次轉錄整個資料夾的所有檔案"
DASHBOARD_QUICK_ACTION_URL_DESC = "貼上 YouTube、X 或 Google Drive 連結自動下載"
DASHBOARD_ONBOARDING_TITLE = "歡迎使用 Whisper UI"
DASHBOARD_ONBOARDING_STEP1 = "上傳第一支音訊或影片檔"
DASHBOARD_ONBOARDING_STEP2 = "等待系統辨識並產生轉錄結果"
DASHBOARD_ONBOARDING_STEP3 = "下載 SRT／DOCX 等格式或直接複製文字"
DASHBOARD_ONBOARDING_CTA = "上傳第一支檔案"
DASHBOARD_SPARKLINE_TITLE = "近 7 日新增"

# -- Upload page --
UPLOAD_HEADER = "上傳音訊"
UPLOAD_DESCRIPTION = "上傳音訊或影片檔案進行語音轉錄。"
UPLOAD_SUPPORTED_FORMATS = "支援格式：{formats}"
UPLOAD_CHOOSE_FILE = "選擇檔案"
UPLOAD_LANGUAGE = "語言"
UPLOAD_MODEL = "模型"
UPLOAD_NUM_SPEAKERS = "說話者人數（0 = 自動偵測）"
UPLOAD_ENABLE_DIARIZATION = "啟用說話者分離"
UPLOAD_DIARIZATION_UNAVAILABLE = "說話者分離不可用（未設定 HF_TOKEN）"
UPLOAD_CONVERT_TRADITIONAL = "轉換為繁體中文"
UPLOAD_CONVERT_TRADITIONAL_HELP = "將簡體中文轉錄結果轉換為繁體中文（僅對中文生效）"
UPLOAD_ENABLE_LLM_CORRECTION = "啟用 LLM 文字校驗"
UPLOAD_LLM_CORRECTION_HELP = "使用 Ollama 小模型修正明顯錯字與同音字（僅對中文生效，失敗時自動保留原文）"
UPLOAD_LLM_CORRECTION_UNAVAILABLE = "LLM 文字校驗不可用（未設定 OLLAMA_BASE_URL）"
UPLOAD_START = "開始轉錄"
UPLOAD_ENQUEUE_FAILED = "提交任務時發生錯誤，請稍後再試"
UPLOAD_NO_FILE = "請先上傳檔案。"
UPLOAD_BATCH_EXCEEDS_LIMIT = "最多一次上傳 {limit} 個檔案，目前已選 {count} 個。"
UPLOAD_TAB_FILES = "選擇檔案"
UPLOAD_TAB_FOLDER = "選擇資料夾"
UPLOAD_MODE_GROUP = "上傳模式"
UPLOAD_CHOOSE_FOLDER = "選擇資料夾"
UPLOAD_FOLDER_DESCRIPTION = "選擇包含音訊或影片檔案的資料夾，將自動篩選支援的格式並批次轉錄。"
UPLOAD_NO_SUPPORTED_FILES = "所選檔案中沒有支援的格式。"
UPLOAD_DRAG_DROP = "將檔案拖曳至此處，或點擊下方選擇檔案"
UPLOAD_UPLOADING = "上傳中..."
UPLOAD_FILE_TOO_LARGE = "檔案「{name}」超過大小限制（{limit}）。"
UPLOAD_INVALID_FILE_CONTENT = "檔案「{name}」不是有效的音訊或影片。"
UPLOAD_INVALID_LANGUAGE = "不支援的語言：{value}"
UPLOAD_INVALID_MODEL = "不支援的模型：{value}"
UPLOAD_TAB_URL = "網址下載"
UPLOAD_URL_PLACEHOLDER = "每行一個 YouTube 影片或播放清單、X 或 Google Drive 分享連結..."
UPLOAD_URL_DESCRIPTION = (
    "輸入一個或多個 YouTube 影片或播放清單、X 貼文網址或 Google Drive 分享連結（每行一個），"
    "系統將自動下載並進行轉錄。播放清單會展開為多個任務並以批次顯示。"
)
UPLOAD_URL_PLAYLIST_NOT_SUPPORTED = (
    "不支援自動產生的合輯（Mix）或需要登入的播放清單（稍後觀看、喜歡的影片），請提供公開播放清單或單一影片網址。"
)
UPLOAD_URL_PLAYLIST_TOO_LARGE = "播放清單包含 {count} 部影片，超過單次上限 {limit} 部。"
UPLOAD_URL_PLAYLIST_TOO_LARGE_UNKNOWN = "播放清單影片數超過單次上限 {limit} 部。"
UPLOAD_URL_PLAYLIST_EMPTY = "播放清單中沒有可轉錄的影片。"
UPLOAD_URL_PLAYLIST_UNAVAILABLE = "無法讀取播放清單，可能為私人清單或已被刪除。"
UPLOAD_URL_PLAYLIST_FETCH_FAILED = "讀取播放清單失敗，請稍後再試。"
UPLOAD_URL_DISCLAIMER = (
    "請確認您有權下載該影片內容，並遵守相關服務條款（包含 X／Twitter 與 YouTube）。"
    "Google Drive 檔案需設定為「任何人都可檢視」。"
)
UPLOAD_URL_NO_INPUT = "請輸入至少一個網址。"
UPLOAD_URL_EXCEEDS_LIMIT = "最多一次提交 {limit} 個網址，目前已輸入 {count} 個。"
UPLOAD_URL_ALL_INVALID = "所有輸入的網址格式皆無效，請確認為 YouTube、X 或 Google Drive 連結。"
UPLOAD_PRESET_SECTION = "場景預設"
UPLOAD_PRESET_MEETING = "會議錄音"
UPLOAD_PRESET_PODCAST = "Podcast 整理"
UPLOAD_PRESET_INTERVIEW = "訪談"
UPLOAD_PRESET_LECTURE = "演講課程"
UPLOAD_PRESET_MEETING_DESC = "中文、多語者、開啟說話者分離與校驗"
UPLOAD_PRESET_PODCAST_DESC = "中文、2 名語者、開啟校驗"
UPLOAD_PRESET_INTERVIEW_DESC = "中文、雙語者、保留原始文字"
UPLOAD_PRESET_LECTURE_DESC = "中文、單一講者、開啟校驗"
UPLOAD_PRESET_CUSTOM = "自訂中"
UPLOAD_SECTION_BASIC = "基本設定"
UPLOAD_SECTION_ADVANCED = "進階設定"
UPLOAD_ADVANCED_ENABLED_COUNT = "已啟用 {count} 項"
UPLOAD_ADVANCED_TOGGLE_EXPAND = "展開進階設定"
UPLOAD_ADVANCED_TOGGLE_COLLAPSE = "收起進階設定"
UPLOAD_SUBMIT_STATUS_FILES = "準備轉錄 {count} 個檔案"
UPLOAD_SUBMIT_STATUS_URLS = "準備轉錄 {count} 個網址"
UPLOAD_SUBMIT_STATUS_EMPTY = "尚未選擇來源"
UPLOAD_INFOTIP_LABEL = "查看說明"

# -- Jobs page --
JOBS_HEADER = "任務列表"
JOBS_EMPTY = "尚無任務。前往**上傳**頁面提交檔案。"
JOBS_VIEW = "檢視"
JOBS_WAITING = "等待中..."
JOBS_ERROR = "錯誤：{error}"
JOBS_QUALITY_WARNING_BADGE = "品質警告"
JOBS_RETRY = "重新執行"
JOBS_RETRY_CONFIRM = "確定要重新執行此任務嗎？"
JOBS_RETRY_CONFIRM_BUTTON = "確認重新執行"
JOBS_DELETE = "刪除"
JOBS_DELETE_CONFIRM = "確定要刪除此任務嗎？此操作無法復原。"
JOBS_DELETE_CONFIRM_BUTTON = "確認刪除"
JOBS_RE_TRANSCRIBE = "重新轉換"
JOBS_RE_TRANSCRIBE_TITLE = "以不同設定重新轉換"
JOBS_RE_TRANSCRIBE_DESC = "保留原本的逐字稿，並使用新設定建立一個新版本，無須重新上傳音檔。"
JOBS_RE_TRANSCRIBE_SUBMIT = "建立新版本"
JOBS_RE_TRANSCRIBE_SUCCESS = "已建立新版本並開始轉換"
JOBS_RE_TRANSCRIBE_FAILED = "重新轉換失敗，請稍後再試。"
JOBS_RE_TRANSCRIBE_SOURCE_GONE = "原始音檔已被清理，無法重新轉換，請重新上傳。"
JOBS_VERSION_BADGE = "重新轉換版本"
JOBS_BATCH_LABEL = "批次上傳（{count} 個檔案）"
JOBS_BATCH_LABEL_TITLED = "{title}（{count} 部影片）"
JOBS_BATCH_PROGRESS = "{completed}/{total} 已完成"
JOBS_BATCH_TOGGLE_LABEL = "展開或收合此批次"
JOBS_BATCH_RETRY_ALL = "全部重試"
JOBS_BATCH_RETRY_ALL_CONFIRM = "確定要重新執行此批次中所有失敗的任務嗎？"
JOBS_BATCH_RETRY_ALL_CONFIRM_BUTTON = "確認全部重試"
JOBS_BATCH_DELETE_ALL = "全部刪除"
JOBS_BATCH_DELETE_ALL_CONFIRM = "確定要刪除此批次中所有任務嗎？此操作無法復原。"
JOBS_BATCH_DELETE_ALL_CONFIRM_BUTTON = "確認全部刪除"
JOBS_BATCH_DOWNLOAD = "批次下載"
JOBS_BATCH_DOWNLOAD_FORMAT = "選擇匯出格式"
JOBS_BATCH_DOWNLOAD_BUTTON = "下載 ZIP"
JOBS_FILTER_ALL = "全部"
JOBS_EMPTY_FILTERED = "沒有符合篩選條件的任務。"
JOBS_PAGE_INFO = "第 {current} / {total} 頁（共 {count} 個任務）"
JOBS_PAGE_PREV = "上一頁"
JOBS_PAGE_NEXT = "下一頁"
JOBS_STALE_ERROR = "任務逾時或 Worker 異常終止"
JOBS_TIMEOUT_ERROR = "任務總執行時間超出上限（{seconds} 秒），音檔可能過長或裝置繁忙，請調整 JOB_TIMEOUT_MAX 後重試"
JOBS_SEARCH_PLACEHOLDER = "搜尋檔案名稱或網址..."
JOBS_INLINE_EXPORT = "匯出"
JOBS_SELECT_ROW = "選取此任務"
JOBS_BULK_SELECTED = "已選 {count} 項"
JOBS_BULK_CLEAR_SELECTION = "取消選取"
JOBS_BULK_RETRY = "批次重試"
JOBS_BULK_DELETE = "批次刪除"
JOBS_BULK_EXPORT = "批次匯出"
JOBS_BULK_CONFIRM_RETRY = "確定要重新執行選取的 {count} 個任務嗎？"
JOBS_BULK_CONFIRM_DELETE = "確定要刪除選取的 {count} 個任務嗎？此操作無法復原。"
JOBS_BULK_SUCCESS = "已處理 {count} 個任務"
JOBS_BULK_PARTIAL = "已處理 {ok} 個任務，{failed} 個失敗"
JOBS_BULK_RETRY_HINT = "請選取至少一個失敗的任務"
JOBS_BULK_EXPORT_HINT = "請選取至少一個已完成的任務"

# -- Viewer page --
VIEWER_NOT_FOUND = "找不到該任務。"
VIEWER_NOT_COMPLETED = "任務尚未完成。狀態：{status}"
VIEWER_RESULT_NOT_FOUND = "找不到結果檔案。"
VIEWER_TRANSCRIPT_TITLE = "轉錄結果：{name}"
VIEWER_METADATA = "時長：{minutes}分{seconds}秒 | 段落：{segments} | 語言：{language}"
VIEWER_NO_SEGMENTS = "轉錄結果中無段落資料。"
VIEWER_SEARCH_PLACEHOLDER = "輸入關鍵字篩選..."
VIEWER_SEARCH_NO_RESULTS = "找不到符合的段落。"
VIEWER_SEARCH_DISABLED = (
    "段落過多（{count} 段），已停用即時搜尋以避免瀏覽器卡頓。請改用瀏覽器內建搜尋（Ctrl/Cmd + F）或匯出 TXT 後搜尋。"
)
VIEWER_EMPTY_STATE = "請從上方選擇一個已完成的任務來檢視轉錄結果。"
VIEWER_COPY = "複製全文"
VIEWER_COPIED = "已複製"
VIEWER_EXPORT_TOOLTIPS: dict[str, str] = {
    "srt": "SubRip 字幕格式",
    "vtt": "WebVTT 字幕格式",
    "txt": "純文字格式",
    "json": "JSON 結構化資料",
    "docx": "Word 文件格式",
}
VIEWER_BACK_TO_JOBS = "返回任務列表"
VIEWER_COPY_SEGMENT = "複製此段"
VIEWER_SOURCE_URL = "來源影片"
VIEWER_DOWNLOAD_MEDIA = "下載影片"
VIEWER_SEGMENT_COPIED = "已複製此段"
VIEWER_SHORTCUTS_TITLE = "鍵盤捷徑"
VIEWER_SHORTCUTS_FOCUS_SEARCH = "聚焦搜尋"
VIEWER_SHORTCUTS_NAV = "上一段／下一段"
VIEWER_SHORTCUTS_COPY = "複製目前段落"
VIEWER_SHORTCUTS_CLEAR = "清除搜尋"

# -- Toast --
TOAST_UPLOAD_SUCCESS = "已提交 {count} 個任務"
TOAST_URL_SKIPPED = "，略過 {count} 個無效網址"
TOAST_FILE_SKIPPED = "，略過 {count} 個無效檔案"
TOAST_URL_DEDUPED = "，移除 {count} 個重複網址"
TOAST_UPLOAD_FAILED = "，{count} 個任務提交失敗"
TOAST_NETWORK_ERROR = "網路連線錯誤，請稍後再試"
TOAST_ACTION_FAILED = "操作失敗，請稍後再試"

# -- Theme --
THEME_TOGGLE_LIGHT = "淺色模式"
THEME_TOGGLE_DARK = "深色模式"

# -- Dialog --
DIALOG_CANCEL = "取消"
DIALOG_CONFIRM = "確認"

# -- Authentication --
AUTH_LOGIN_HEADER = "登入"
AUTH_LOGIN_DESCRIPTION = "請輸入您的帳號與密碼。"
AUTH_USERNAME = "使用者名稱"
AUTH_USERNAME_HELP = "3-32 字元，僅允許英文字母、數字、底線與連字號"
AUTH_PASSWORD = "密碼"
AUTH_PASSWORD_HELP = "至少 8 個字元"
AUTH_LOGIN_BUTTON = "登入"
AUTH_LOGOUT_BUTTON = "登出"
AUTH_REGISTER_HEADER = "註冊帳號"
AUTH_REGISTER_DESCRIPTION = "建立新帳號以開始使用 Whisper UI。"
AUTH_REGISTER_BUTTON = "建立帳號"
AUTH_BOOTSTRAP_HEADER = "建立管理員帳號"
AUTH_BOOTSTRAP_DESCRIPTION = "首次使用，請建立第一個管理員帳號。此帳號將擁有人員管理與檢視所有任務的權限。"
AUTH_BOOTSTRAP_WARNING = "你正在建立系統第一個管理員帳號，請妥善保管登入資訊。"
AUTH_PASSWORD_SHOW = "顯示密碼"
AUTH_PASSWORD_HIDE = "隱藏密碼"
AUTH_LOGIN_FAILED = "帳號或密碼錯誤，請再試一次。"
AUTH_ACCOUNT_INACTIVE = "此帳號已停用，請聯絡管理員。"
AUTH_USERNAME_TAKEN = "此使用者名稱已被使用，請選擇另一個。"
AUTH_USERNAME_INVALID = "使用者名稱格式無效（3-32 字元，僅英文字母、數字、底線與連字號）。"
AUTH_PASSWORD_TOO_SHORT = "密碼長度至少 8 個字元。"
AUTH_LOGIN_LINK = "已有帳號？前往登入"
AUTH_REGISTER_LINK = "尚未有帳號？前往註冊"
AUTH_SIGNED_IN_AS = "登入身分：{username}"
AUTH_ADMIN_BADGE = "管理員"
AUTH_RATE_LIMITED = "嘗試次數過多，請於 {minutes} 分鐘後再試。"
AUTH_REGISTER_RATE_LIMITED = "註冊次數過多，請稍後再試。"

# -- Admin --
ADMIN_USERS_HEADER = "使用者管理"
ADMIN_USERS_DESCRIPTION = "新增、停用、變更權限或重設密碼。停用會立即作廢該使用者所有 session。"
ADMIN_USER_COL_USERNAME = "使用者"
ADMIN_USER_COL_ROLE = "角色"
ADMIN_USER_COL_STATUS = "狀態"
ADMIN_USER_COL_CREATED = "建立時間"
ADMIN_USER_COL_JOBS = "任務數"
ADMIN_USER_COL_ACTIONS = "操作"
ADMIN_USER_ROLE_ADMIN = "管理員"
ADMIN_USER_ROLE_USER = "一般使用者"
ADMIN_USER_STATUS_ACTIVE = "啟用"
ADMIN_USER_STATUS_INACTIVE = "停用"
ADMIN_ACTION_DEACTIVATE = "停用"
ADMIN_ACTION_ACTIVATE = "啟用"
ADMIN_ACTION_PROMOTE = "升為管理員"
ADMIN_ACTION_DEMOTE = "撤銷管理員"
ADMIN_ACTION_RESET_PASSWORD = "重設密碼"
ADMIN_ADD_USER_HEADER = "新增使用者"
ADMIN_ADD_USER_SUBMIT = "建立帳號"
ADMIN_RESET_PASSWORD_HEADER = "重設 {username} 的密碼"
ADMIN_RESET_PASSWORD_SUBMIT = "確認重設"
ADMIN_LAST_ADMIN_ERROR = "系統至少需要一位啟用中的管理員，無法執行此操作。"
ADMIN_SELF_ACTION_ERROR = "不能對自己執行此操作。"
ADMIN_USER_NOT_FOUND_ERROR = "找不到指定的使用者，可能已被刪除。"
ADMIN_JOBS_HEADER = "所有任務"
ADMIN_JOBS_DESCRIPTION = "顯示系統中所有使用者的任務（包含沒有擁有者的歷史資料）。"
ADMIN_JOBS_OWNER_UNKNOWN = "（無擁有者）"
ADMIN_NAV_USERS = "使用者"
ADMIN_NAV_JOBS = "所有任務"


# -- Status display --
STATUS_LABELS: dict[str, str] = {
    "pending": "等待中",
    "queued": "排隊中",
    "processing": "處理中",
    "completed": "已完成",
    "failed": "失敗",
}
