from __future__ import annotations

# String truncation lengths
ERROR_MAX_LENGTH = 1000
ERROR_DISPLAY_LENGTH = 200
MESSAGE_MAX_LENGTH = 500
STDERR_MAX_LENGTH = 500
JOB_ID_DISPLAY_LENGTH = 8
TIMESTAMP_DISPLAY_LENGTH = 19

# List limits
DEFAULT_JOB_LIST_LIMIT = 50

# Timeouts (seconds)
FFMPEG_CONVERT_TIMEOUT = 300
FFPROBE_TIMEOUT = 30
SQLITE_BUSY_TIMEOUT_MS = 5000

# Redis expiry (seconds)
REDIS_PROCESSING_EXPIRY = 7200  # 2 hours
REDIS_COMPLETED_EXPIRY = 86400  # 24 hours
REDIS_FAILED_EXPIRY = 86400  # 24 hours
